### ISSUE TITLE
Nested DEFUNs are bad

### ISSUE THREAD

**Issue by lispm** [mark-watson/loving-common-lisp#1]
(let ((foo ...))
  (defun bar () ...))

DEFUN is not recognized by the compiler as a top-level definition. DEFUN etc. are best used as top-level forms.

Code like in nested.lisp makes no sense at all. Every time the function TEST runs it redefines the global function NESTED-FUNCTION!

Local functions in Common Lisp are introduced by FLET or LABELS. Nesting DEFUNs is almost always the wrong thing.

**Comment by whitten** [comment]
So I'm an admitted newbie here, but it seems if you had a function that you were memo-izing
(where you checked the values of argument and returned a pre-computed result) then one way of doing this would involve redefining the global function each time it is used to "hard bake" the calculated value already.  This seems efficient in time, if definitely not in space.

Or am I missing some crucial insight ?

**Comment by lispm** [comment]
Why would you want to do that? If the function retrieves a value from a variable, you don't need to redefine the function. If you put the value as data into the function, then it would make even less sense.

Doubly nested DEFUNs are in Lisp not used. I've never seen it used. DEFUN is for defining top-level functions at the top-level. FLET and LABELS is for defining local lexical functions.

Singly nested DEFUNs inside LETs for closures are also a bad style. Creating global closures at load time is not that great as a tool.

**Comment by mark-watson** [comment]
Thanks lispm, that is a valid point. It is an old habit of mine in both Scheme and Common Lisp to "hide" local functions inside the function that uses them.
