### ISSUE TITLE
double-args looks useless as a macro...

### ISSUE THREAD

**Issue by lispm** [mark-watson/loving-common-lisp#2]
Does the macro in macro2.lisp make sense?

How is it supposed to be used?

Check the expansions of (double-args x) and (double-args x y) etc. Don't know what it is supposed to do...

**Comment by mark-watson** [comment]
I agree. I think that I am going to drop the macro material in its entirety in the next edition of the book. I am not sure what, but I will add new material (probably an NLP example that I am using in a Haskell book I am working on - recoded in CL).

Thanks for your comments! Often pointing out bad material is the most useful type of comment.
